datasets:
  sat_scores:
    file: "data/SAT.csv"
    description: "SAT Scores Analysis"
    dependent_var: "sat"
    label_var: "state"
    predictors:
      - name: "expend"
        label: "Expenditure"
      - name: "ratio"
        label: "Student-Teacher Ratio"
      - name: "salary"
        label: "Teacher Salary"
      - name: "frac"
        label: "Fraction Taking SAT"
  
  census_wages:
    file: "data/census.csv"
    description: "Census Wage Analysis"
    dependent_var: "wage"
    label_var: "sector"
    predictors:
      - name: "educ"
        label: "Years of Education"
      - name: "exper"
        label: "Years of Experience"
      - name: "age"
        label: "Age"
      - name: "race"
        label: "Race"
      - name: "sex"
        label: "Sex"
      - name: "union"
        label: "Union Membership"
      - name: "married"
        label: "Marital Status"
      - name: "south"
        label: "Southern Region"
      - name: "hispanic"
        label: "Hispanic Origin"

  galton_heights:
    file: "data/galton.csv"
    description: "Galton Family Heights Study"
    dependent_var: "height"
    label_var: "family"
    predictors:
      - name: "father"
        label: "Father's Height"
      - name: "mother"
        label: "Mother's Height"
      - name: "sex"
        label: "Sex"
      - name: "nkids"
        label: "Number of Children"

  auto_mpg:
    file: "data/auto-mpg.csv"
    description: "Auto MPG Analysis"
    dependent_var: "mpg"
    label_var: "car_name"
    predictors:
      - name: "cylinders"
        label: "Number of Cylinders"
      - name: "displacement"
        label: "Engine Displacement"
      - name: "horsepower"
        label: "Horsepower"
      - name: "weight"
        label: "Vehicle Weight"
      - name: "acceleration"
        label: "Acceleration"
      - name: "model_year"
        label: "Model Year"
      - name: "origin"
        label: "Origin"

  # Example of another dataset configuration
  # housing_prices:
  #   file: "data/housing.csv"
  #   description: "Housing Prices Analysis"
  #   dependent_var: "price"
  #   label_var: "address"
  #   predictors:
  #     - name: "sqft"
  #       label: "Square Footage"
  #     - name: "bedrooms"
  #       label: "Number of Bedrooms"
  #     - name: "age"
  #       label: "House Age" 